/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalgame;

import finalgame.lib.Engine.GameLoop;
import finalgame.lib.GraphicsEngine.Renderer;
import finalgame.world.World;

public class App {

    
    /** 
     * @param args
     */
    public static void main(String[] args) {
      World.init();
      GameLoop.start();
      Renderer.init();
    }
}
