/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package finalgame;

import finalgame.lib.Engine.GameLoop;
import finalgame.lib.GraphicsEngine.Renderer;

public class App {

    public static void main(String[] args) {
      Renderer.init();
      GameLoop.start();
    }
}
